#!/bin/sh

set -e

if [ -z "$CACHER" ]; then
  MIRROR="http://ftp.debian.org/debian/"
  MIRROR_SECURITY="http://security.debian.org/"
else
  MIRROR="http://$CACHER/ftp.debian.org/debian/"
  MIRROR_SECURITY="http://$CACHER/security.debian.org/"
fi

lb config noauto \
    --apt apt \
    --apt-indices false \
    --apt-recommends false \
    --architecture amd64 \
    --archive-areas 'main contrib non-free' \
    --debian-installer true \
    --zsync false \
    --debug \
    --distribution wheezy \
    --iso-application 'Huayra GNU/Linux' \
    --iso-publisher 'Conectar Igualdad; http://www.conectarigualdad.gob.ar/; info@conectarigualdad.gob.ar' \
    --iso-volume 'Huayra GNU/Linux' \
    --keyring-packages 'debian-archive-keyring huayra-archive-keyring mate-archive-keyring' \
    --parent-mirror-chroot $MIRROR \
    --parent-mirror-chroot-security $MIRROR_SECURITY \
    --parent-mirror-chroot-updates $MIRROR \
    --mirror-debian-installer $MIRROR \
    --system live \
    "${@}"
